import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/shared/Navbar'
import SideNavbar from './components/shared/SideNavbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Food Network',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <SideNavbar>
          {children}
        </SideNavbar>

      </body>
    </html>
  )
}
